- request:
    method: GET
    url: ^/rest/project/creation$
  response:
    status: 200
    headers:
      content-type: application/json+hal
    body:
      _links:
        self:
          href: http://localhost:8000/rest/project/creation
        save:
          href: http://localhost:8000/rest/project/save
      tasks:
        - id: 1
          name: Task 1
        - id: 2
          name: Task 2
        - id: 3
          name: Task 3
        - id: 4
          name: Task 4
        - id: 5
          name: Task 5
      project:
        name: null
        description: null
        tasks: null

- request:
    method: POST
    url: ^/rest/project/save$
  response:
    status: 200
    headers:
      content-type: application/json+hal
    body:
      location: http://localhost:8000/rest/project/1/creationConfirmation

- request:
    method: GET
    url: ^/rest/project/1/creationConfirmation$
  response:
    status: 200
    headers:
      content-type: application/json+hal
    body:
      _links:
        self:
          href: http://localhost:8000/rest/project/1/creationConfirmation
        creation:
          href: http://localhost:8000/rest/project/creation
        edit:
          href: http://localhost:8000/rest/project/1/edit

- request:
    method: GET
    url: ^/rest/project/search$
    query:
      name: a
      description: b
      tasks: 1
      page: 0
      size: 2
  response:
    status: 200
    headers:
      content-type: application/json+hal
    body:
      _links:
        self:
          href: http://localhost:8000/rest/project/search?name=a&description=b&tasks=1&page=0&size=2
        search:
          href: http://localhost:8000/rest/project/search{?name,description,tasks*,page,size}
          templated: true
        otherResult:
          href: http://localhost:8000/rest/project/search/result{?name,description,tasks*,page,size}
          templated: true
        result:
          href: http://localhost:8000/rest/project/search/result?name=a&description=b&tasks=1&page=0&size=2
      form:
        options:
          name: a
          description: b
          tasks: [1]
        tasks:
          - id: 1
            name: Task 1
          - id: 2
            name: Task 2
          - id: 3
            name: Task 3
          - id: 4
            name: Task 4
          - id: 5
            name: Task 5

- request:
    method: GET
    url: ^/rest/project/search$
    query:
      name: a
      description: b
      tasks: 1
      page: 1
      size: 2
  response:
    status: 200
    headers:
      content-type: application/json+hal    
    body:
      _links:
        self:
          href: http://localhost:8000/rest/project/search?name=a&description=b&tasks=1&page=1&size=2
        search:
          href: http://localhost:8000/rest/project/search{?name,description,tasks*,page,size}
          templated: true
        otherResult:
          href: http://localhost:8000/rest/project/search/result{?name,description,tasks*,page,size}
          templated: true
        result:
          href: http://localhost:8000/rest/project/search/result?name=a&description=b&tasks=1&page=1&size=2
      form:
        options:
          name: a
          description: b
          tasks: [1]
        tasks:
          - id: 1
            name: Task 1
          - id: 2
            name: Task 2
          - id: 3
            name: Task 3
          - id: 4
            name: Task 4
          - id: 5
            name: Task 5

- request:
    method: GET
    url: ^/rest/project/search$
    query:
      name: a
      description: b
      tasks: 1
      page: 2
      size: 2
  response:
    status: 200
    headers:
      content-type: application/json+hal
    body:
      _links:
        self:
          href: http://localhost:8000/rest/project/search?name=a&description=b&tasks=1&page=2&size=2
        search:
          href: http://localhost:8000/rest/project/search{?name,description,tasks*,page,size}
          templated: true
        otherResult:
          href: http://localhost:8000/rest/project/search/result{?name,description,tasks*,page,size}
          templated: true
        result:
          href: http://localhost:8000/rest/project/search/result?name=a&description=b&tasks=1&page=2&size=2
      form:
        options:
          name: a
          description: b
          tasks: [1]
        tasks:
          - id: 1
            name: Task 1
          - id: 2
            name: Task 2
          - id: 3
            name: Task 3
          - id: 4
            name: Task 4
          - id: 5
            name: Task 5

- request:
    method: GET
    url: ^/rest/project/search$
  response:
    status: 200
    headers:
      content-type: application/json+hal
    body:
      _links:
        self:
          href: http://localhost:8000/rest/project/search
        search:
          href: http://localhost:8000/rest/project/search{?name,description,tasks*,page,size}
          templated: true
        otherResult:
          href: http://localhost:8000/rest/project/search/result{?name,description,tasks*,page,size}
          templated: true
      form:
        options:
          name:
          description:
          tasks:
        tasks:
          - id: 1
            name: Task 1
          - id: 2
            name: Task 2
          - id: 3
            name: Task 3
          - id: 4
            name: Task 4
          - id: 5
            name: Task 5

- request:
    method: GET
    url: ^/rest/project/search/result$
    query:
      name: a
      description: b
      tasks: 1
      page: 0
      size: 2
  response:
    status: 200
    headers:
      content-type: application/json+hal
    body:
      _links:
        self:
          href: http://localhost:8000/rest/project/search/result?name=a&description=b&tasks=1&page=0&size=2
      page: 0
      size: 2
      total: 5
      _embedded:
        projects:
          - _links:
              self:
                href: http://localhost:8000/rest/project/1/summary
              edit:
                href: http://localhost:8000/rest/project/1/edit
            id: 1
            name: Project 1
            description: First project
          - _links:
              self:
                href: http://localhost:8000/rest/project/2/summary
            id: 2
            name: Project 2
            description: Second project

- request:
    method: GET
    url: ^/rest/project/search/result$
    query:
      name: a
      description: b
      tasks: 1
      page: 1
      size: 2
  response:
    status: 200
    headers:
      content-type: application/json+hal
    body:
      _links:
        self:
          href: http://localhost:8000/rest/project/search/result?name=a&description=b&tasks=1&page=1&size=2
      page: 1
      size: 2
      total: 5
      _embedded:
        projects:
          - _links:
              self:
                href: http://localhost:8000/rest/project/3/summary
            id: 3
            name: Project 3
            description: Third project
          - _links:
              self:
                href: http://localhost:8000/rest/project/4/summary
              edit:
                href: http://localhost:8000/rest/project/4/edit
            id: 4
            name: Project 4
            description: Fourth project

- request:
    method: GET
    url: ^/rest/project/search/result$
    query:
      name: a
      description: b
      tasks: 1
      page: 2
      size: 2
  response:
    status: 200
    headers:
      content-type: application/json+hal
    body:
      _links:
        self:
          href: http://localhost:8000/rest/project/search/result?name=a&description=b&tasks=1&page=2&size=2
      page: 2
      size: 2
      total: 5
      _embedded:
        projects:
          - _links:
              self:
                href: http://localhost:8000/rest/project/5/summary
              edit:
                href: http://localhost:8000/rest/project/5/edit
            id: 5
            name: Project 5
            description: Fifith project

- request:
    method: GET
    url: ^/rest/project/1/edit
  response:
    status: 200
    headers:
      content-type: application/json+hal
    body:
      _links:
        self:
          href: http://localhost:8000/rest/project/1/edit
        save:
          href: http://localhost:8000/rest/project/1/save
        deletionConfirmation:
          href: http://localhost:8000/rest/project/1/deletionConfirmation
      tasks:
        - id: 1
          name: Task 1
        - id: 2
          name: Task 2
        - id: 3
          name: Task 3
        - id: 4
          name: Task 4
        - id: 5
          name: Task 5
      project:
        name: Project 1
        description: First project
        tasks: [1, 4, 5]

- request:
    method: POST
    url: ^/rest/project/1/save$
  response:
    status: 200
    headers:
      content-type: application/json+hal
    body:
      location: http://localhost:8000/rest/project/1/saveConfirmation
      
- request:
    method: GET
    url: ^/rest/project/1/saveConfirmation$
  response:
    status: 200
    headers:
      content-type: application/json+hal
    body:
      _links:
        self:
          href: http://localhost:8000/rest/project/1/saveConfirmation
        edit:
          href: http://localhost:8000/rest/project/1/edit
        search:
          href: http://localhost:8000/rest/project/search

- request:
    method: GET
    url: ^/rest/project/1/deletionConfirmation$
  response:
    status: 200
    headers:
      content-type: application/json+hal
    body:
      _links:
        self:
          href: http://localhost:8000/rest/project/1/deletionConfirmation
        delete:
          href: http://localhost:8000/rest/project/1/delete

- request:
    method: POST
    url: ^/rest/project/1/delete$
  response:
    status: 200
    headers:
      content-type: application/json+hal
    body:
      location: http://localhost:8000/rest/project/deletionSuccess

- request:
    method: GET
    url: ^/rest/project/deletionSuccess$
  response:
    status: 200
    headers:
      content-type: application/json+hal
    body:
      _links:
        self:
          href: http://localhost:8000/rest/project/deletionSuccess
        search:
          href: http://localhost:8000/rest/project/search